### ISSUE TITLE
Passport Github Example

### ISSUE THREAD

**Issue by michaelerobertsjr** [strongloop/loopback-example-passport#103]
This example is needed, most engineers are going to want Github over social logins.

I found that the way to get Github to work as a provider I had to provide the entire url for my app as the `callbackURL`.  It would be great if this were better documented.  It took a ton of guessing and errors to get it working.  I'll open a pr with a better example if someone can't.

```
  "github": {
    "provider": "github",
    "module": "passport-github",
    "strategy": "OAuth2Strategy",
    "clientID": process.env.GITHUB_CLIENT_ID,
    "clientSecret": process.env.GITHUB_CLIENT_SECRET,
    "callbackURL": "https://my.app.com/auth/github/callback",
    "authPath": "/auth/github",
    "callbackPath": "/auth/github/callback",
    "successRedirect": "/auth/account",
    "failureRedirect": "/login",
    "scope": ["email", "profile"],
    "failureFlash": true
  }
```

**Comment by dhmlau** [comment]
@michaelerobertsjr , please feel free to submit a PR! Thanks.
