### ISSUE TITLE
Compatible with Loopback 4?

### ISSUE THREAD

**Issue by DanielChuDC** [strongloop/loopback-example-passport#117]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@DanielChuDC, this example repo is for LoopBack 3, so I believe it won't work with LoopBack 4. 
To see how to add passport authentication to a LoopBack 4 application, please see the information from: https://www.npmjs.com/package/@loopback/authentication-passport.  

Please also refer to [this blog](https://strongloop.com/strongblog/loopback-4-authentication-updates/) for the LB4 authentication module. 

Hope it helps.
