### ISSUE TITLE
ldap configuration

### ISSUE THREAD

**Issue by dennyabuti** [strongloop/loopback-example-passport#12]
I am trying to configure passport for authentication with an ldap provider using passport-ldapauth
 "ldap": {
    "provider": "ldap",
    "authScheme":"ldap",
    "module": "passport-ldapauth",
    "authPath": "/auth/ldap",
    "server":{
      "url": "ldap://server:10389/o=org,dc=domain,dc=com",
      "adminDn": "uid=admin,ou=system",
      "adminPassword": "pwd",
      "searchBase": "ou=users,o=org,dc=domain,dc=com",
      "searchFilter": "(cn={{username}})"
    }
  }

Everything seems to be working fine until the point where done(err, user, authInfo) is called inside loginCallback(req, done) defined in passport-configurator.js.

TypeError: undefined is not a function

Where is the done closure supposed to be defined?

Thanks for your help!

**Comment by OwenBrotherwood** [comment]
@raymondfeng I think something should be stated in the docs as it does not seem that LDAP works "out of the box" despite it being mentioned in https://strongloop.com/strongblog/authenticate-loopback-google-facebook-github/

FYI current Community work for LDAP as far as I know:
- Origins https://github.com/strongloop/loopback-component-passport/pull/44
- My fork https://github.com/OwenBrotherwood/loopback-example-passport

Strongloop may be supporting LDAP for it's own customers: I am free wheeling on freely available code

Strongloop should probably deceide it's buisness needs concerning support of LDAP to allow MS-AD  Authentication/Authorization or, as Microsoft has support for OAuth, deceide that until a customer needs it, to not support it

**Comment by crandmck** [comment]
@raymondfeng This seems reasonable to me.  Please confirm if you think I should update the docs as stated above.

**Comment by OwenBrotherwood** [comment]
@crandmck 
LDAP has been merged LDAP https://github.com/strongloop/loopback-component-passport/commit/ae998bba2fd8205d3df7dd9f46de25d73061d588 

Example of how to use LDAP MS-AD:
 may be needed the merge allows the possibility for using: let us see if there comes an issue from the users but prepare use cases for the use of internal authentication/authorization where loopback is used where the focus is not on creation of app/api/gui but on the centralised (security department) type of aproach for role management.

Signarture of passport:
 I have another use case that allows me to investigate signature and if it is possible to use Microsoft centric method(s) for passport. 
It could be important to ensure Microsoft's passport solution as a Strongloop strategic/archetectural priority
https://github.com/AzureAD/passport-azure-ad

**Comment by crandmck** [comment]
Thanks @OwenBrotherwood I would like to add this to the docs, but I really need and example of how to configure it; something along the lines of [what we have now for FaceBook and Google](http://docs.strongloop.com/pages/viewpage.action?pageId=3836277#Third-partylogin(Passport)-Configuringthird-partyproviders).

Can you provide such an example?

**Comment by OwenBrotherwood** [comment]
@crandmck 
Pierre has tested for LDAP OpenLDAP : config https://github.com/strongloop/loopback-component-passport/pull/44#issuecomment-91611286 

I will provide a config for LDAP MS AD (Microsoft Active Directory) that shows general configuration type values with some "getting started" comments.

**Comment by OwenBrotherwood** [comment]
@crandmck 
The doc should indicate some form of early support 

https://github.com/strongloop/loopback-component-passport/issues/58 The callback works in the context  ms-ad LDAP "works for me" 

```
"ms-ad": {
    "provider": "ms-ad",
    "authScheme":"ldap",
    "module": "passport-ldapauth",
    "authPath": "/auth/msad",
    "successRedirect": "/auth/account",
    "failureRedirect": "/msad",
    "failureFlash": true,
    "session": true,
    "LdapAttributeForLogin": "mail",
    "LdapAttributeForUsername": "mail",
    "LdapAttributeForMail": "mail",
    "server":{
      "url": "ldap://ldap.example.org:389/dc=example,dc=org",
      "bindDn": "bindUsername",
      "bindCredentials": "bindPassword",
      "searchBase": "ou=people,dc=example,dc=org",
      "searchAttributes": ["cn", "mail", "uid", "givenname"],
      "searchFilter": "(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))"
    }
  },
``

**Comment by crandmck** [comment]
OK, I added this to http://docs.strongloop.com/pages/viewpage.action?pageId=3836277#Third-partylogin(Passport)-Configuringthird-partyproviders.  Please take a look.

**Comment by OwenBrotherwood** [comment]
@crandmck Looks good. Let us see what issues there are in order to pin down key problems for doc.

My current workload is: 
- AAA in general (the issue I created, I don't want to name the issue or too much noise in github x-ref comments)
- ADFS, alternative to LDAP to support AA in an enterprise https://github.com/AzureAD/passport-azure-ad/issues/25#issuecomment-96264123 
- passport in general: make sure I understand it
- customCallback introduced in LDAP Pull Request: what does it do

**Comment by OwenBrotherwood** [comment]
# Comments on LDAP MS-AD
- In  general, if you neet to use a  LDAP MS-AD, then one needs to make friends with the friendly MS AD guy in the organisation.
- The example config is a general pointer for the MS AD guy to what is needed. 
- Make sure that you have a small test app that is only what is needed to check that you get the results you expected

**Comment by OwenBrotherwood** [comment]
Comments on passport to an alternative to accessing MS-AD instead of via LDAP: ADSF (for anyone finding this pull request and is wondering how to integrate to MS-AD
It is hoped to show this at some time, but currently causing me headaches
https://github.com/AzureAD/passport-azure-ad/issues/25
