### ISSUE TITLE
accessToken

### ISSUE THREAD

**Issue by SSchaaf** [strongloop/loopback-example-passport#24]
accesssToken is not generated when a local login used within app (firing http://localhost:3005/auth/local)

With API login accessToken is generated (firing http://localhost:3005/api/users/login)

I commented "enableAuth()"  in server\boot\authentication.js and used explorer to monitor accesToken data.

**Comment by PierreGambarotto** [comment]
In [`passport-configurator.js`](https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L213)  from loopback-component-passport, you can see on line 213 that the token is created if the `setAccessToken` option exists.

Try to put `setAccessToken: true` in your providers.json in the part describing the `local` provider.
Not tested, but I hope this will help. And maybe this should be in a documentation somewhere, or even already is :-)

**Comment by SSchaaf** [comment]
Tks Pierre. Works for me.
But I needed to change "loopback-component-passport": "^1.0.5", in loopback-example-passport package.json file to the last version, 1.1.2
