### ISSUE TITLE
unlink / revoke ?

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-example-passport#26]
Hi, is it possible to unlink / revoke an account?

**Comment by cadesalaberry** [comment]
Hi, I would also like to know more about unlinking an account.

**Comment by cadesalaberry** [comment]
Hey there, I still would like to get an answer :smile:

**Comment by orosznyet** [comment]
I'm with you.

**Comment by cadesalaberry** [comment]
@kjdelisle @jannyHou @loay @b-admike @ssh24 @virkt25 @dhmlau

Can we have some guidelines to achieve unlinking/revocation of a passport account ?

Cheers,
