### ISSUE TITLE
/link/facebook 404 not found

### ISSUE THREAD

**Issue by heygrady** [strongloop/loopback-example-passport#28]
From the Account page (/auth/account) there is a button for "Link Facebook." That button takes you to the /link/facebook page, which is a 404 page. How is this supposed to work?

**Comment by jforaker** [comment]
+1

**Comment by jannyHou** [comment]
same as https://github.com/strongloop/loopback-example-passport/issues/46
I will fix that missing page in a few days. Thanks!
