### ISSUE TITLE
Add support for Microsoft Azure Active Directory Apps

### ISSUE THREAD

**Issue by RainerAtSpirit** [strongloop/loopback-example-passport#29]
Currently there are two node libraries that support azure active directory. Would be great to see an example how the passport version could be supported here

https://github.com/AzureAD/passport-azure-ad

As an alternative there's a core ADAL node library as well.

https://github.com/AzureAD/azure-activedirectory-library-for-nodejs

**Comment by OwenBrotherwood** [comment]
@raymondfeng 
After the LDAP (MS AD) pull is over for the loopback-component-passport, is there a good use case for trying to test Azure ?
The request is for an example as to how to create a working config. Some of the understanding is the same as the LDAP (MS AD).
I have a MS Developer Account that gives me free credits to set up an Azure AD "at some  time"

**Comment by OwenBrotherwood** [comment]
@raymondfeng 
I will be testing https://github.com/AzureAD/passport-azure-ad for in house use.
And will probably test with loopback-component-passport if you can indicate there are no others working on this at the moment.

I found my own Use Case for http://en.wikipedia.org/wiki/Active_Directory_Federation_Services

**Comment by OwenBrotherwood** [comment]
https://github.com/AzureADSamples/AzureAD-Node-Sample/wiki/Windows-Azure-Active-Directory-WebSSO-using-WS-Federation-with-passport.js
Something someone should walk thru when they have time
