### ISSUE TITLE
Need clarification - inconsistencies

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-example-passport#3]
@raymondfeng The example models.json has all core loopback models redeclared with a lowercased model name, and then pointing to the actual base model. Why this differentiation? Wouldn't you be able to extend the core models otherwise? Note that:

`loopback.getModel('user') !== loopback.getModel('User')` whereas:

`loopback.models.user === loopback.models.User` 

due to how the model name is normalized in several ways. This is bad practice IMHO - we need to be more explicit and it would help if there was a recommended naming scheme.

**Comment by aukevs** [comment]
+1

**Comment by raymondfeng** [comment]
We plan to get rid of the name mangling business when a model is registered with `app.models` (maybe in LoopBack 3.0)
