### ISSUE TITLE
Adding additional parameters to oAuth request

### ISSUE THREAD

**Issue by SyRenity** [strongloop/loopback-example-passport#40]
Is there any way to add additional parameters to the OAuth2 request?

Similar to:
https://testing/oauth/authorize?
    response_type=code&
    client_id=YOUR_CLIENT_ID&
    redirect_uri=YOUR_CALLBACK_URL&
    scope=send&
    meta[test1]=1&
    meta[test2]=2&
    meta[test3]=3

**Comment by raymondfeng** [comment]
You can subclass a given oAuth2 strategy to override the following methods:

https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L247-L278
