### ISSUE TITLE
loopback.getCurrentContext() returns empty {} for "active"

### ISSUE THREAD

**Issue by gianko** [strongloop/loopback-example-passport#41]
Extending this example to have an "Events" model I have this js

<pre>
var loopback = require('loopback');
module.exports = function(Event) {

  Event.observe('before save', function (ctx,next) {
    
    var context = loopback.getCurrentContext();
    console.log('context:', context.active);
    next();
  });

};
</pre>

The console shows an empty {}

Doing some testing I think it has somethign to do with this:

<pre>
app.middleware('auth', loopback.token({
  model: app.models.AccessToken
}));
</pre>

**Comment by yuanyong** [comment]
@gianko I've got the same issue too. Just as you mentioned, we need to remove:
```
app.middleware('auth', loopback.token({
  model: app.models.AccessToken
}));
```
While it works with:
```
app.use(loopback.token());
```
I think the example might need a update incase others have this issue.
