### ISSUE TITLE
Passport login does not set req.accessToken

### ISSUE THREAD

**Issue by mikesparr** [strongloop/loopback-example-passport#43]
Other LB apps leverage the `User.login()` which returns an `accessToken` and also set in the request. This token is then used for subsequent requests to API, etc.  In this example app since it uses Passport's `req.login()` it bypasses LB's built in accessToken to leverage the ACL and Roles (RBAC).

What is the best way to incorporate Passport, but also include LB's built in user model and RBAC?  Is there some remote hook after login with passport (local or social strategies) that we can then do additional logic?

**Comment by barboni** [comment]
@mikesparr did you make any progress on this? I'm currently facing the same issue.

**Comment by julien-sarazin** [comment]
@mikesparr all auth informations are stored in req.signedCookies. 
I'm currently working on it. I think i will try to put in the `auth:after` middleware something like:
 ``req.accessToken = req.signedCookies.access_token``

I'll try to keep you updated if it works fine with the built-in ACL.

**Comment by julien-sarazin** [comment]
Not woring ATM : https://github.com/strongloop/loopback/issues/1747

**Comment by julien-sarazin** [comment]
If you guys are still interested in a solution check the strongloop/loopback#1747.
cheers

**Comment by barboni** [comment]
@julien-sarazin thanks a lot. I actually ended up re-implementing the component for our needs, but I'll definitely check out your solution.

**Comment by jannyHou** [comment]
thanks @everyone here! And thanks you @julien-sarazin for your workaround solution in  https://github.com/strongloop/loopback/issues/1747#issuecomment-149874893
