### ISSUE TITLE
Question on providers.json.template

### ISSUE THREAD

**Issue by adriatic** [strongloop/loopback-example-passport#44]
Except for "local strategy" all other providers x-login and x-link section in the template. What is the meaning of that and where can I read more about it?

**Comment by jannyHou** [comment]
hey @adriatic , to answer your question, let me give you a brief description about what is `loopback-component-passport`:
It is a third-party login component, in this example app, you could provide your social account info in provider.json, like replace [`login`](https://github.com/strongloop/loopback-example-passport/blob/master/providers.json.template#L15-L16) and [`link`](https://github.com/strongloop/loopback-example-passport/blob/master/providers.json.template#L55-L56) snippet with your own fb app id, then after you run `node .` and open `localhost:3000`, you can login with fb account, or create your local account and link fb to it.
For more details please check our [Documentation](https://docs.strongloop.com/pages/releaseview.action?pageId=3836277)
And my suggestion is, if you have develop app from fb or google, please try it, then you would have a much clear idea about what's happening with passport. 
Hope this would be helpful for you. And for future references, please ask questions on [google group](https://groups.google.com/forum/#!forum/loopbackjs) Thanks!

**Comment by sochka** [comment]
Could you add other passport modules, not just google/twitter/facebook?

**Comment by jannyHou** [comment]
hey @sochka, I think as a demo, these three most popular accounts give users a clear idea about how passport work in loopback. If you have other good suggestions, please feel free to open a new issue and create a pull request to implement it! Thanks!

**Comment by sochka** [comment]
@jannyHou, well, actually I didn't ask you to implement it :) I just asked if this feature already exists. I should have said "Could I add..?". From your answer, I assume right now you cannot use passport-Vkontakte-token with loopback, right?

**Comment by jannyHou** [comment]
@sochka it's not supported yet but you can submit a patch in `loopback-component-passport` to add it:
Add your new case here:
https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L204
