### ISSUE TITLE
can you provide full documentation link about strong loop passport on Facebook login

### ISSUE THREAD

**Issue by vishaloban** [strongloop/loopback-example-passport#47]
I unable to run this example can you provide documentation link not strongloop site i also see it .

**Comment by raymondfeng** [comment]
Can you elaborate the issue/error you ran into?

**Comment by vishaloban** [comment]
Thank sir for helping on this topic, you provide the git link working fine.

**Comment by superkhau** [comment]
@vishaloban Has the issue been resolved? Can I close it?

**Comment by superkhau** [comment]
Closing due to no response for almost a month.
