### ISSUE TITLE
Can not use useridentity in Loopback-passport

### ISSUE THREAD

**Issue by OnlyRefat** [strongloop/loopback-example-passport#48]
Loopback-passport is awesome i think. i have looked through the example. i set it up with the following command
npm install loopback-component-passport

Now when i want to use the **userIdentity** as a base class i dont find it in the list. what is the problem. how can i make userIdentity and userCredential available that i can use them as a base class to create new. 
Regards,
Refat.

**Comment by loay** [comment]
Not exactly sure what you mean by the list?
If you mean explorer operation list , it is normal as it is set by default in model-config.json to 
```
 "public": false
```
The user identity file itself could be found here:
...\node_modules\loopback-component-passport\lib\models

Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
