### ISSUE TITLE
Facebook no longer returns all fields by default

### ISSUE THREAD

**Issue by clockworkgr** [strongloop/loopback-example-passport#50]
More of a heads up for  anyone coming across this.

New Apps created in facebook automatically get v2.4 + Graph API and both versioned/unversioned requests are upgraded to 2.4.

Hence:
https://graph.facebook.com/v2.2/me with ClientID/ClientSecret from a new app returns ONLY id + name. Even though it's versioned it uses v2.4+)

In order to return to the old behaviour and get the same fields we need to explicitly call

https://graph.facebook.com/v2.2/me?fields=first_name,gender,last_name,link,locale,name,timezone,verified,email,updated_time

This is possible with the profileFields field in the AuthStrategy options.

So providers.json.template should include:

```
"profileFields": ["gender","link","locale","name","timezone","verified","email","updated_time"],
```
for the facebook-login provider to function as expected

**Comment by jannyHou** [comment]
@clockworkgr Thanks for informing us this change! I will look into it.

**Comment by jannyHou** [comment]
hey @clockworkgr, thank you! your solution works fine, the complete link returns a bunch of information. But we would appreciate it to be a user defined behaviour :) so feel free to change it on your own app, modify this line would be ok: https://github.com/jaredhanson/passport-facebook/blob/master/lib/strategy.js#L59

**Comment by jannyHou** [comment]
Thanks @loay ! For declaring this implementation in `loopback-component-passport` [README.md](https://github.com/strongloop/loopback-component-passport)

**Comment by princecharmx** [comment]
@clockworkgr  suggestions looks more clean than the suggestion of changing the profileUrl in the code.

`providers.json.template should include:
"profileFields": ["gender","link","locale","name","timezone","verified","email","updated_time"],`

**Comment by ggiacomo** [comment]
OMG why this solution is not in the official documentation?! 
Please update this page
https://docs.strongloop.com/display/public/LB/Tutorial%3A+third-party+login

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@superkhau I updated http://loopback.io/doc/en/lb2/Configuring-providers.json.html#example-providersjson but now we need to update as well https://github.com/strongloop/loopback-example-passport/blob/master/providers.json.template.  I'll leave that to you or @jannyHou.

**Comment by jannyHou** [comment]
Thank you @crandmck . Created a pr to update it in example repo:
https://github.com/strongloop/loopback-example-passport/pull/83
