### ISSUE TITLE
http://localhost:3000/api/users makes 404, not 401

### ISSUE THREAD

**Issue by sanori** [strongloop/loopback-example-passport#56]
It seems that loopback.rest() does not work, due to the mixing of app.middleware() calls and middleware.json.

I'll submit pull request to fix this.

**Comment by loay** [comment]
Hi @sanori 
Your commit here https://github.com/sanori/loopback-example-passport/commit/d97664b7e0191d0dede7b0b0d8c1d4db7b39c69a
does actually solve the 404 raiseUrlNotFoundError
The PR gives accesstoken error. Can you do a PR with the commit? Thanks.

**Comment by loay** [comment]
I submitted another fix, that is slightly different than yours for the 404 error. 
For the PR that gives accesstoken error, please fix it and ping me to merge it. Thanks.
