### ISSUE TITLE
logout does not remove or invaidate access_token in cookie

### ISSUE THREAD

**Issue by sanori** [strongloop/loopback-example-passport#58]
Subject says it all.

It seems that req.logout() only removes user profiles.
Since access_token is still valid for api, next user can access previous user's resources.

**Comment by sanori** [comment]
codes in https://github.com/strongloop/loopback-component-passport/issues/57#issuecomment-140929082 may solve this problem.

**Comment by jannyHou** [comment]
Closing it due to duplicate, thanks for your understanding.
https://github.com/strongloop/loopback-component-passport/issues/57
