### ISSUE TITLE
How to get more data using remote method.

### ISSUE THREAD

**Issue by yadavji83** [strongloop/loopback-example-passport#62]
currently when i do:
https://fightraffic.herokuapp.com/api/users/34/?ACCESS_TOKEN

I get:
{"realm":null,"username":"google-login.111111111","credentials":null,"challenges":null,"email":"yadavji83@gmail.com","emailVerified":null,"verificationToken":null,"status":null,"created":null,"lastUpdated":null,"id":12}

I want more data from useridentity.profile model.

**Comment by artmunro** [comment]
hey yadavji83 .. I was faced with same thing.. here is what i did for facebook (can be same for others)..
Basically 3 Steps.
1. Add Profile fields to providers
2. Update user-identity.js to set additional fields 
3. add fields in user.jaso to hold the new fields

Details..
Step 1 - sample providers
  "facebook-login": {
    "provider": "facebook",
    "module": "passport-facebook",
    "clientID": "123xxxx",
    "clientSecret": "123xxx",
    "callbackURL": "/auth/facebook/callback",
    "authPath": "/auth/facebook",
    "callbackPath": "/auth/facebook/callback",
    "successRedirect": "/auth/account",
    "failureRedirect": "/login",
    "scope": ["email"],
    "failureFlash": true,
    "profileFields": ["id", "emails", "displayName", "last_name", "first_name", "gender","age_range", "link", "timezone", "is_verified"]
    },
Note scope and profileFields from above.

STEP 2 - update user-identity (there is a better way of doing this but this gets you going..)
node_modules/loopback-component-passport/lib/models/user-identity.js
Need to update - function profileToUser(provider, profile, options) {} line 54 by adding  for example..

   if (email) {
      userObj.email = email;
    }
      if (gender) {
      userObj.gender = gender;
    }

Step 3 - add the fields gender to the model user.json (follow slc arc or cli to add the fields.

hope this helps.  I would be interested in other opinions n what should be done for real contribution...

**Comment by jannyHou** [comment]
thank you @artmunro ! Your solutions are welcomed!
And please also check issue https://github.com/strongloop/loopback-example-passport/issues/50 for more details!
