### ISSUE TITLE
Current build isn't working

### ISSUE THREAD

**Issue by redaikidoka** [strongloop/loopback-example-passport#63]
After npm install succeeeds, I run node and get an error:
```
/login-sample/loopback-example-passport/server/server.js:180
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
                                                  ^
ReferenceError: baseUrl is not defined
    at Server.<anonymous> (/Users/pol/Dev/ilp/login-sample/loopback-example-passport/server/server.js:180:51)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:129:20)
    at net.js:1171:12
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/Users/pol/Dev/ilp/login-sample/loopback-example-passport/node_modules/async-listener/index.js:19:15)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by loay** [comment]
@redaikidoka 
Thanks fore reporting the issue. Having a look. Thanks.

**Comment by loay** [comment]
@redaikidoka 

in `server/server.js`
just this line:
```      var baseUrl = app.get('url');
```
above this:
```
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
```

I am fixing the build shortly, so the new one works soon.

**Comment by redaikidoka** [comment]
;) I just removed the baseUrl reference and it worked fine.

On Tue, Jan 5, 2016 at 2:20 PM, Loay Gewily <notifications@github.com>
wrote:

> @redaikidoka <https://github.com/redaikidoka>
>
> in server/server.js
> just this line:
> ``` var baseUrl = app.get('url');
>
> above this:
>
>   console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
>
>
> I am fixing the build shortly, so the new one works soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-example-passport/issues/63#issuecomment-169151959>
> .
>



-- 

-=-=-==-=-=-=-==-=-=-=-=-=-=-=-=-=-
Pol Stafford
Storyteller, Writer, Geek, Sensei

**Comment by loay** [comment]
@redaikidoka Code is updated
