### ISSUE TITLE
can't API login a local strategy user

### ISSUE THREAD

**Issue by msimonc** [strongloop/loopback-example-passport#65]
After creating a user with the 'local' strategy using the built in client, I can't login using the 'user' API.

**Comment by jannyHou** [comment]
@msimonc can you provide a sandbox to reproduce your issue? 
https://github.com/strongloop/loopback-sandbox/tree/master/server
You can fork this repo and update it with your own code. Thanks!

**Comment by doktordirk** [comment]
had that 'error' myself ... until i realized that i restarted the server and the in memory database got naturally reset. without restarting the server (or writing the db to file), it worked fine.
so my guess is, that this issue can be closed.

**Comment by jannyHou** [comment]
@doktordirk  good to know that you solved the problem! Thanks I am closing it and feel free to reopen it if you have further questions.
