### ISSUE TITLE
Cannot GET /auth/facebook

### ISSUE THREAD

**Issue by msimonc** [strongloop/loopback-example-passport#66]
I deployed to AWS so that Facebook would have an URL to callback to, but, when Facebook did so it console logs: 

Error: Cannot GET /auth/facebook

**Comment by jannyHou** [comment]
hey @msimonc here is a detailed steps of how to get access to facebook account:
https://github.com/strongloop/loopback-example-passport/blob/master/README.md#2-get-your-client-idssecrets-from-third-partysocial-logins
Hope it could solve your problem!
