### ISSUE TITLE
Update to documentation: Facebook profile info via providers.json

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/loopback-example-passport#68]
I followed one of the tutorials and the Stopwatch example.
https://github.com/vkarpov15/stopwatch-server-example/
https://github.com/vkarpov15/stopwatch-example

The documentation does not seem to have the crucial info that changing the providers.json scope and profileFields can provide more information from Facebook.

I experimented with it to find it out, so I thought I'd just add it in here. The profile info shows up under the UserIdentity model.
```javascript
   "scope": ["public_profile","email","user_birthday"],
	"profileFields":["id","displayName","gender","email","age_range","photos","birthday"]
}
```
It mentions it here https://docs.strongloop.com/display/LB/Tutorial%3A+third-party+login
but it is a little vague and suggests changing the JavaScript of the module, which was unnecessary for me.

**Comment by jannyHou** [comment]
thank you @alexxgathp , I think both of them work, it depends on user's preference.
