### ISSUE TITLE
After google redirection, ensureLoggedIn fails to detect user is connected and redirects to login page

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback-example-passport#75]
I have an issue regarding the ensureLoggedIn.

```
app.get('/auth/account', ensureLoggedIn('/login'), function (req, res, next) {
  console.log("Hello there !");
  res.render('pages/loginProfiles', {
    user: req.user,
    url: req.url
  });
});
```

Here is the flow to create this issue:
1. I create a local user, then link this new account to google.
2. I am properly redirected back from google after I accepted to authorize the app.
3. I end up on `auth/account` (as the `console.log("Hello there!")` tells me), and I am immediately redirected back to the `login` page.

I suppose ensureLoggedIn fails to detect that a user is connected, which explains why it redirects me immediately to `login`.

Am I the only one to have this behavior ?

**Comment by ntrinquier** [comment]
No you're not, I have the same issue. I've also noticed that the `user` is not in the response. This might or might not be related.
