### ISSUE TITLE
Please provide example with GitHub Integration

### ISSUE THREAD

**Issue by tconroy** [strongloop/loopback-example-passport#76]
Hi! I'm trying to integrate with GitHub Enterprise login and running into issues ( discussed here https://github.com/strongloop/loopback-component-passport/issues/143 )

If someone could provide an example of this integrated with strategy-github passport auth, it'd be greatly appreciated. :)

**Comment by richardpringle** [comment]
I agree that an example with GitHub would be great!

**Comment by cristtopher** [comment]
and local with mongoDb example too.

**Comment by chalettu** [comment]
Any updates on this?

**Comment by perceptron007** [comment]
Plese provide at least one example for something working. Make it Facebook, Google, Twitter anything but atleast one working example would be great.
