### ISSUE TITLE
update this old piece of code

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-example-passport#77]
I don't want to come across harsh like an old teacher, but please make this repo conform your own instructions on your blog, as this is currently not the preferred approach. It should have a boot script for the configuration.

Also, try to put yourself in the perspective of the end user and modify the example to use custom models. It is the preferred approach, as to have extensibility down the line.

**Comment by superkhau** [comment]
This repo definitely needs an update. Which blog article are you refering to? Can you paste a link here?

**Comment by Morriz** [comment]
Sure, I read this blog:

https://strongloop.com/strongblog/part-1-ionic-loopback-node-js-mobile/

**Comment by perceptron007** [comment]
Is anyone going to work on it or not ?
This is so irresponsible, how can you boast about features that you didn't tell how they work ?
