### ISSUE TITLE
Refactor the example

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-example-passport#78]
This example is out-of-date so I am opening a story to refactor it, let's keep all discussions here and any suggestions are welcomed!
- [ ] Combine it with angular use cases. Details see https://github.com/strongloop/loopback-component-passport/issues/26
- [ ] In slc loopback, add an option to enable users choose different authentication level for a certain api

**Comment by jannyHou** [comment]
Related: https://github.com/strongloop/loopback-example-passport/issues/32

**Comment by artmunro** [comment]
Any idea when this will be refactored ?
