### ISSUE TITLE
local login is not working

### ISSUE THREAD

**Issue by lepus2** [strongloop/loopback-example-passport#88]
I'd like to apply loopback-passport so that I have tried 'loopback-example-passport'. I clone this repository and modify provider.json a bit. (Facebook id and secret...) There's nothing more I have changed. I succeeded to Facebook login but I was not able to login locally. I can make a new ID by '/signup' page and I checked out in db.json. However, when I tried to login with the account I just made up, they said "Invalid username/password or email has not been verified"

I think something wrong with the source but I couldn't figure it out. Please help me with this issue!!

Thanks in advance :)

**Comment by overfried** [comment]
Hi lepus2 ...The signup workflow is not setting the user email as verified. Take a look at this example: https://github.com/strongloop/loopback-example-user-management/blob/master/common/models/user.js#L5-L35

**Comment by smith64fx** [comment]
in the loopback-example-passport this command here has no effect.

```
User.afterRemote('create', function(context, user, next) {
```

**Comment by smith64fx** [comment]
I'm really desperated right now, don't know what to do =/

The local login is not working so the whole project here makes no sense.

**Comment by smith64fx** [comment]
@lepus2 
@overfried 

I made a fork and also a pull request to fix this problem!

You can get it here:
https://github.com/schmidigital/loopback-example-passport

**Comment by smith64fx** [comment]
The problem why this happened is here:

https://github.com/strongloop/loopback-component-passport/commit/4cf8153a7b11ace76bf75977fa9ca238cf8910ad#diff-0d9ea68c1756ce2fc5c960b5796850aaR307

They added email verification as a must-have but didn't care about the email verification process itself ;)

**Comment by haotangio** [comment]
Hi all,

Any update for this issue?
The library is quite useful but this issue is very annoying.

**Comment by perceptron007** [comment]
@smith64fx Have you implemented this passport-connector for other login module too. I am trying to crete a passport login via LinkedIN and Google also in Loopback and i have no idea how to do this. I tried to learn by using example but i have found that it already have a lot of issues. If you have created your application can you tell me how to do it ??
